


-- 1
SELECT EMP_ID ,EMP_NAME ,PHONE ,HIRE_DATE ,DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE
					WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';



-- 2
SELECT EMP_ID ,EMP_NAME ,PHONE , SALARY , JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY = (SELECT MAX(SALARY)
				FROM EMPLOYEE
				WHERE EXTRACT (YEAR FROM HIRE_DATE) > '2000');


-- 3
SELECT EMP_ID ,EMP_NAME ,DEPT_CODE ,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
WHERE (DEPT_CODE,JOB_CODE) = (SELECT DEPT_CODE ,JOB_CODE 
								FROM EMPLOYEE
								WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';
			
-- 4
SELECT EMP_ID , EMP_NAME ,DEPT_CODE ,JOB_CODE , TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE
NATURAL JOIN JOB
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE (DEPT_TITLE,JOB_NAME) = (SELECT DEPT_TITLE, JOB_NAME
								FROM EMPLOYEE
								NATURAL JOIN JOB
								JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
								WHERE EXTRACT(YEAR FROM HIRE_DATE) = '2000');

-- 5
SELECT EMP_ID ,EMP_NAME ,DEPT_CODE ,MANAGER_ID ,EMP_NO  ,TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE,MANAGER_ID) = (SELECT DEPT_CODE ,MANAGER_ID
							FROM EMPLOYEE
							WHERE SUBSTR(EMP_NO,8,1) = 2
							AND SUBSTR(EMP_NO,1,2) = 77);

-- 6
SELECT EMP_ID , EMP_NAME ,NVL(DEPT_TITLE, '소속없음') , JOB_NAME, TO_CHAR(HIRE_DATE, 'YY/MM/DD') 
FROM EMPLOYEE MAIN
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE)
					FROM EMPLOYEE SUB
					WHERE (ENT_YN = 'N' AND SUB.DEPT_CODE = MAIN.DEPT_CODE) 
					OR (ENT_YN = 'N' AND SUB.DEPT_CODE IS NULL AND MAIN.DEPT_CODE IS NULL) 
)
ORDER BY HIRE_DATE ;

-- 7
SELECT EMP_ID , EMP_NAME ,JOB_NAME,
TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(EMP_NO, 1, 6),'RRMMDD'))/12) "나이",
TO_CHAR((SALARY + (SALARY * NVL(BONUS, 0)))*12, 'L999,999,999')"보너스 포함 연봉"
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE (JOB_NAME,EMP_NO)  IN (SELECT JOB_NAME, MAX(EMP_NO)
							FROM EMPLOYEE
							NATURAL JOIN JOB
							GROUP BY JOB_NAME
							)
ORDER BY 나이 DESC;

SELECT EMP_ID , EMP_NAME ,JOB_NAME,
TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(EMP_NO, 1, 6),'RRMMDD'))/12) "나이",
TO_CHAR((SALARY + (SALARY * NVL(BONUS, 0)))*12, 'L999,999,999')"보너스 포함 연봉"
FROM EMPLOYEE MAIN
JOIN JOB J ON(MAIN.JOB_CODE = J.JOB_CODE)
WHERE EMP_NO = (SELECT MAX(EMP_NO) 
				FROM EMPLOYEE SUB
				WHERE MAIN.JOB_CODE = SUB.JOB_CODE)
ORDER BY 나이 DESC;



------------------------------------------

SELECT DEPT_TITLE, JOB_NAME, EMP_NAME , EMAIL 
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
LEFT JOIN JOB USING(JOB_CODE)
WHERE JOB_NAME = '대리'
ORDER BY EMP_NAME ;















