
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER example IDENTIFIED BY "example2";


GRANT RESOURCE, CONNECT TO example;


ALTER USER example DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;



ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER example2 IDENTIFIED BY "example2";
GRANT CREATE SESSION TO example2;
GRANT CREATE TABLE TO example2;
ALTER USER example2 DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;
GRANT SELECT ON EMPLOYEE TO example2;

REVOKE SELECT ON EMPLOYEE FROM example2;
REVOKE CONNECT, RESOURCE, DBA FROM example2;
DROP USER example2 CASCADE;


CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20) ,
	DEKETE_YN CHAR(1) DEFAULT 'N' CHECK(DEKETE_YN IN('Y','N'))
);
COMMIT;

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN "MEMBER".PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN "MEMBER".DEKETE_YN IS '삭제여부';
COMMIT;

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER PRIMARY KEY,
	"BOARD_TITLE"	VARCHAR2(300) NOT NULL,
	"BAORD_CONTENT"	VARCHAR2(4000) NOT NULL,
	"BOARD_WRITER"	NUMBER,
	"CREATE_DATE"	DATE	DEFAULT	SYSDATE NOT NULL,
	FOREIGN KEY ("BOARD_WRITER") REFERENCES "MEMBER" (MEMBER_NO)
);
COMMIT;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '글번호';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '글제목';
COMMENT ON COLUMN "BOARD"."BAORD_CONTENT" IS '글내용';
COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS '작성자';
COMMENT ON COLUMN "BOARD"."CREATE_DATE" IS '작성일자';
COMMIT;

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100; 

CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1;
COMMIT;


INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step1', 'step11', '-', DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step2', 'step22', '010-1111-2222', DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step3', 'step33', '-', DEFAULT);
COMMIT;


INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '첫 글', '스탭평가', 100, DEFAULT);

INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '두 번째 글', '재밌다', 300, DEFAULT);

INSERT INTO "BOARD"
VALUES(SEQ_BOARD_NO.NEXTVAL, '세 번째 글', '하하하', 200, DEFAULT);

COMMIT;

SELECT BOARD_NO, BOARD_TITLE, BAORD_CONTENT, MEMBER_ID, CREATE_DATE
FROM "BOARD"
FULL JOIN "MEMBER" ON (BOARD_WRITER = MEMBER_NO)
ORDER BY 1 DESC;


