
-- 1. 학생 이름 주소지
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY 1;


-- 2. 휴학중 학생 이름, 주민번호, 나이 오름차순

SELECT STUDENT_NAME "학생 이름", STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;


-- 3. 주소지 강원도, 경기도 학번 1900년대 
--		이름 학번 주소   이름 오름차순

SELECT STUDENT_NAME "학생 이름", STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND (STUDENT_ADDRESS LIKE '%강원도%'OR STUDENT_ADDRESS LIKE '%경기도%')
ORDER BY 1 ;


-- 4. 법학과 교수 나이 많은사람 순

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2;


-- 5. 2004/2학기 'C3118100' 과목 수강한 학생들의 학점 조회.   학점이 높은 학생부터
-- 		학점 같으면 학번 낮은 학생부터   TO_CHAR(NUMBER, 'FM9.00')

SELECT STUDENT_NO , TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND SUBSTR(TERM_NO, 1, 4) = 2004
AND SUBSTR(TERM_NO, 6, 1) = 2
ORDER BY 2 DESC, 1;


-- 6. 학생 번호, 학생 이름, 학과 이름을 학생 이름으로 오름차순 출력
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME 
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;


-- 7. 춘 대학교 과목 이름, 과목 학과 이름 출력
SELECT CLASS_NAME ,DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


-- 8. 과목별 교수 이름 (과목이름, 교수이름) 출력
SELECT CLASS_NAME ,PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO);


-- 9. 8번 결과 중 '인문 사회'계열에 속한 과목의 교수 이름 출력
SELECT CLASS_NAME ,PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CATEGORY = '인문사회';


-- 10. 음악학과 학생들의 평점
--		학번, 학생이름, 전체 평점 (소수점 1자리  반올림)
SELECT STUDENT_NAME, ROUND(AVG(POINT),1) 
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NAME;


-- 11. A313047 의 지도교수
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM  TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE COACH_PROFESSOR_NO = (SELECT COACH_PROFESSOR_NO
							FROM  TB_STUDENT
							WHERE STUDENT_NO = 'A313047')
AND STUDENT_NO = 'A313047';


-- 12. 2007년에 인간관계론 과목 수강한 학생의 이름과 수강학기 표시
SELECT STUDENT_NAME , TERM_NO
FROM TB_STUDENT
LEFT JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NO = (SELECT CLASS_NO 
					FROM TB_CLASS 
					WHERE CLASS_NAME = '인간관계론')
AND SUBSTR(TERM_NO,1,4) = '2007'
ORDER BY 1;





-- 13. 예체능 계열 과목 중 담당교수 배정 못받은 과목의 과목이름, 학과이름 출력


SELECT CLASS_NAME, DEPARTMENT_NO 
FROM TB_DEPARTMENT
FULL JOIN TB_CLASS USING(DEPARTMENT_NO)
FULL JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;


-- 14. 서반아어학과 학생들의 지도교수 출력
--		지도교수 없을경우 "지도교수 미지정" 고학번 학생 우선 출력
SELECT STUDENT_NAME, DECODE(COACH_PROFESSOR_NO, NULL, '지도교수 미지정', PROFESSOR_NAME)
FROM TB_STUDENT TS
LEFT JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT TD ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;


-- 15. 휴학생 아닌 학생중 평점 4.0이상인 학생의 
--	   학번, 이름, 학과이름, 평점 출력
SELECT STUDENT_NO 학번,STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO,STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4 
ORDER BY 1;


-- 16. 환경조경학과 전공 과목들의 과목 별 평점

SELECT CLASS_NO, CLASS_NAME , TRUNC(AVG(POINT),8)  
FROM TB_GRADE
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NO IN (SELECT CLASS_NO
					FROM TB_DEPARTMENT
					JOIN TB_CLASS USING(DEPARTMENT_NO)
					WHERE DEPARTMENT_NAME = '환경조경학과'
					AND CLASS_TYPE = '전공선택')
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;


-- 17. 최경희 학생과 같은 과 학생들의 이름 주소 출력
SELECT STUDENT_NAME ,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
						FROM TB_STUDENT
						WHERE STUDENT_NAME = '최경희');


-- 18. 국어국문학과 중 총 평점이 가장 높은 학생의 이름 학번					

SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NAME,STUDENT_NO, AVG(POINT)학점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE CLASS_NO IN (SELECT CLASS_NO 
					FROM TB_CLASS	
					WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
											FROM TB_DEPARTMENT
											WHERE DEPARTMENT_NAME = '국어국문학과'))
GROUP BY STUDENT_NAME, STUDENT_NO
ORDER BY 학점 DESC)
WHERE ROWNUM = 1;

					
-- 19. '환경조경학과'가 속한 같은 계열의 학과 별 전공과목 평점


SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_DEPARTMENT
LEFT JOIN TB_STUDENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_GRADE USING(STUDENT_NO) 
WHERE CATEGORY = (SELECT CATEGORY
					FROM TB_DEPARTMENT		
					WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;




















































